<?php namespace app\modules\testnay\widgets;

use yii\bootstrap\ActiveForm;
use yii\bootstrap\ActiveField;

class MyActiveForm extends ActiveForm
{
    /**@var ActiveField[] */
    private $_activeFields = [];

    public function init()
    {
        if (count($this->_activeFields)){
            ob_start();
            foreach ($this->_activeFields as $field){
                echo $field;
            }
        }

        parent::init(); // TODO: Change the autogenerated stub

    }

    public function addField($field)
    {
        $this->_activeFields[] = $field;
    }
}