<?php namespace app\modules\testnay\widget\optionlabel;

use yii\base\Widget;
use app\modules\testnay\models\Options;
use yii\data\ActiveDataProvider;
use yii\bootstrap\Html;


class OptionFieldGrid extends Widget{


    public $form;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}