<?php namespace app\modules\testnay\widgets\formrender;

use app\modules\testnay\Testnay;
use yii\base\Widget;
use yii\bootstrap\ActiveForm;
use app\modules\testnay\models\fields\TextFieldModel;
use app\modules\testnay\widgets\MyActiveForm;
use app\modules\testnay\models\Options;
use yii\data\ActiveDataProvider;
use yii\bootstrap\Html;
use Yii;


class FormRender extends Widget{

    /**@var MyActiveForm $form */
    public $form;
    public $fieldModels;

    private $activeForm;
    private $activeFields;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        /**@var TextFieldModel $model */
        foreach ($this->fieldModels as $model){
            $this->activeFields[] = $model->createActiveField($this->form);
            $this->form->addField( $model->createActiveField($this->form) );
        }
    }

    public function run()
    {
        return $this->render('index', ['form' => $this->activeForm , 'fields' => $this->activeFields]);
    }
}